# Generated by Django 3.1.1 on 2020-10-14 23:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tecnology', 'Tecnology'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('Arts', 'Arts'), ('Curiosity', 'Curiosity'), ('Science', 'Science'), ('Self-improvement', 'Self-improvement')], default='arts', max_length=23),
            preserve_default=False,
        ),
    ]
