# Generated by Django 3.1.1 on 2020-10-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_like_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='sdsvsdv'),
            preserve_default=False,
        ),
    ]
