# Generated by Django 3.1.1 on 2020-10-15 00:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('Arts', 'Arts'), ('Curiosity', 'Curiosity'), ('Science', 'Science'), ('Self-improvement', 'Self-improvement')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Technology', 'Technology'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('Arts', 'Arts'), ('Curiosity', 'Curiosity'), ('Science', 'Science'), ('Self-improvement', 'Self-improvement')], max_length=23),
        ),
    ]
